### ISSUE TITLE
[CLI] Deleting all seq frome store

### ISSUE THREAD

**Issue by karoltylenda** [scramjetorg/transform-hub#1018]
**Feature description**
We can remove all sequences from HUB by using `si seq prune`
This functionality will be helpful in sequence store.

**Comment by alicja-gruzdz** [comment]
please place the method to remove all Sequences from Sequence Store under the command:
`si store ...`

**Comment by alicja-gruzdz** [comment]
https://github.com/scramjetorg/transform-hub/pull/1036
thanks @gzukowski :)
