### ISSUE TITLE
[BUG] Missed error handling when we start bugged sequence

### ISSUE THREAD

**Issue by karoltylenda** [scramjetorg/transform-hub#1019]
**Describe the bug**
When we start bugged sequence, CLI doesn't inform us about error.

**Steps to Reproduce**
1. checkout to reconnect branch `git checkout -b feat/reconnect`
2. run sth `yarn start`
3. deploy bugged sequence

***Reproduction repo/branch***
1. `git checkout -b feat/reconnect`

**Version (please complete the following information):**
 - STH version: 1.0
 - node version: 18.19
 - os: macOs Sonoma

**Additional information like logs, screenshots etc.**
![Zrzut ekranu 2024-01-23 o 11 28 35](https://github.com/scramjetorg/transform-hub/assets/64743034/244cf76a-0720-4440-89bc-c7722af70df4)
![Zrzut ekranu 2024-01-23 o 11 28 06](https://github.com/scramjetorg/transform-hub/assets/64743034/5e0e3f07-199d-4c40-bb76-65795aa2a796)

**Comment by patuwwy** [comment]
10be6f2864ee88118a322b0ca44457e461bedcc3
