### ISSUE TITLE
STH Runner exits with code 1

### ISSUE THREAD

**Issue by alicja-gruzdz** [scramjetorg/transform-hub#161]
**Describe the bug**
The Runner exits with code 1 on the STH versions 0.12 and 0.13.

**Steps to Reproduce**
1. `DEVELOPMENT=true scramjet-transform-hub --no-docker`
2. Download and run the sample: https://github.com/scramjetorg/scramjet-cloud-docs/tree/main/samples/test-output
3. In the logs, we should see the error as attached on the screenshot. The Instance API output is unavailable. 

**Expected behavior**
The output stream of  the Instance should be accessible by Instance API.

**Version (please complete the following information):**
 - STH version: 0.13
 
**Additional information like logs, screenshots etc.**
![image](https://user-images.githubusercontent.com/8177865/145370269-f492ebee-31d9-484c-a453-adbf04cdecac.png)

**Comment by MichalCz** [comment]
@pietrzakacper identified that the issue is caused by hard coding the location of the runner path which changes after install from npm (the previous path does not exist anymore). Fix underway.
