### ISSUE TITLE
Containers are not being closed.

### ISSUE THREAD

**Issue by luccam-scr** [scramjetorg/transform-hub#19]
**Describe the bug**

Containers created by host are not being removed by runner.

**Steps to Reproduce**
1. Start a test locally, for instance: yarn test:bdd 
2. Press Ctrl+C
3. run `docker ps` - see the containers still running.

```
08:26 $ docker ps
CONTAINER ID   IMAGE                                            COMMAND                  CREATED       STATUS       PORTS     NAMES
9f92adaa22ae   repo.int.scp.ovh/scramjet/runner:0.10.0-pre.10   "/entrypoint.sh star…"   2 hours ago   Up 2 hours             upbeat_mclaren
4d1c0eeb416e   repo.int.scp.ovh/scramjet/runner:0.10.0-pre.10   "/entrypoint.sh star…"   2 hours ago   Up 2 hours             vigorous_thompson
8cea46502d41   repo.int.scp.ovh/scramjet/runner:0.10.0-pre.10   "/entrypoint.sh star…"   2 hours ago   Up 2 hours             jolly_swartz
```

**Expected behavior**

After a host crash or exit the containers should be removed (either by runner itself or by the host in `process.on("SIGINT")` and `process.on("SIGTERM")` - and preferably both).

**Comment by MichalCz** [comment]
This seems to be solved. Will re-run tests later today
