### ISSUE TITLE
Decrease time of execution of BDD tests by killing instances 

### ISSUE THREAD

**Issue by pietrzakacper** [scramjetorg/transform-hub#193]
Runner has an exit delay. Some of the tests need to it to be able to get the instances streams even after the sequence has finished processing. After BDD tests perform those queries we can just kill the instances using `kill` endpoint and decrease the time we wait for the process to exit.

**Comment by alicja-gruzdz** [comment]
I agree, while doing so we should only make sure we also test for the proper closing of the Instances that should terminate by themselves.
