### ISSUE TITLE
Should we delete fifo on sequence end?

### ISSUE THREAD

**Issue by luccam-scr** [scramjetorg/transform-hub#21]
https://github.com/scramjetorg/transform-hub/blob/86932c6475cc10924d3cf997e2c7c0ad892417c3/packages/adapters/src/sequence-adapter.ts#L181
This deletes fifos dir, while it should be in instance? Please check

**Comment by MichalCz** [comment]
I think we can close this. We should probably read everything before we close off the instance, but that's in another place.
