### ISSUE TITLE
STH crashes when it receives improperly formatted log

### ISSUE THREAD

**Issue by jan-warchol** [scramjetorg/transform-hub#231]
**Describe the bug**
Log messages sent from runner to STH must be valid JSON or STH will crash.

**Steps to Reproduce**
`{"ts": 1643391383251, "level": "ERROR", "msg": "I say "foo" and it fails."}` (notice wrong quoting)

**Expected behavior**
Malformed log message is dropped, but STH continues to work.

**Version (please complete the following information):**
 - STH version: current tip of `release/0.15`, with object logger

**Comment by patuwwy** [comment]
Expected behavior should send error log telling about this error

pt., 28 sty 2022, 18:43 użytkownik Jan Warchoł ***@***.***>
napisał:

**Comment by patuwwy** [comment]
https://github.com/scramjetorg/transform-hub/pull/232

**Comment by patuwwy** [comment]
#232 merged

**Comment by MichalCz** [comment]
Checkend and no longer occurs.
