### ISSUE TITLE
Tests needed for sequence that fails.

### ISSUE THREAD

**Issue by luccam-scr** [scramjetorg/transform-hub#24]
This condition needs to be tested - we need a check if this actually fails if a sequence throws an error.

https://github.com/scramjet-cloud-platform/scramjet-csi-dev/blob/3c0fb5273c147415a390b1cc7007024af20438e2/packages/supervisor/src/lib/lifecycle-controller.ts#L117-L130

**Comment by alicja-gruzdz** [comment]
Performing a container snapshot has never been implemented and it was just a "placehold" condition (aka @TODO).
After refactoring the Supervisor, which was removed and pulled into [CSIController](https://github.com/scramjetorg/transform-hub/blob/release/0.16/packages/host/src/lib/csi-controller.ts), we removed this condition completely.
We are for now planning to support saving and restoring an Instance state using a different approach.
