### ISSUE TITLE
Sequence generator

### ISSUE THREAD

**Issue by patuwwy** [scramjetorg/transform-hub#242]
**Sequence generator**
I would like to create new sequence. I think the easiest way is to copy one of existing sequences from reference-apps dir and then do the cleanup/renaming and package.json adjustment.

Sequences generator will help developer with this process! 

Imagine executing command like `si create awesome-seq --lang=ts` is creating directory with package.json containing just needed (or/and recommended) deps, instaling them, set the name, version. I could just go to index.ts and fill the array of functions :)

**Comment by alicja-gruzdz** [comment]
That's a cool idea

**Comment by jan-warchol** [comment]
I have another idea: what about being able to run single-file sequences without package.json at all? As far as I understand, the only thing that sth actually requires to run a sequence is the info what the entrypoint is (the `main` attribute). In case of single file  this is obvious, and for the other we could have some sensible defaults.

**Comment by patuwwy** [comment]
@jan-warchol
We can discuss this idea but please create new feature request for it.
