### ISSUE TITLE
Runner is not killed by InstanceAdapter when not responding to KILL/STOP control msg

### ISSUE THREAD

**Issue by pietrzakacper** [scramjetorg/transform-hub#258]
**Describe the bug**
Technically everything works correctly bc our Runner is made in such a way that it always politely quits when asked.
Practically part of our code in CSIController will never be executed leading to  stale containers/processes if runner doesn't exit on its own.

The bug was introduced after absorbing supervisor to CSIController. Specifically it's all the control stream handlers that won't be executed, such as:
https://github.com/scramjetorg/transform-hub/blob/release/0.16/packages/host/src/lib/csi-controller.ts#L285
https://github.com/scramjetorg/transform-hub/blob/release/0.16/packages/host/src/lib/csi-controller.ts#L305

What will happen is the REST API (`_kill`, `_stop`) will pipe the control message to the control ***downstream*** and the `communicationHandler` will only dispatch the control messages to handlers from ***upstream***

The fix would be to intercept REST API request, run the handlers in CSIControllers and the send it on control stream

**Comment by patuwwy** [comment]
Probably related to #206, #244

**Comment by patuwwy** [comment]
Especially to https://github.com/scramjetorg/transform-hub/issues/206#issuecomment-1030082183
