### ISSUE TITLE
[Feature] Add the possibility of send data to topics via multiple POST requests.

### ISSUE THREAD

**Issue by MichalCz** [scramjetorg/transform-hub#260]
**Feature description**

Currently data must be sent to the sequence as one long stream (i.e. long running POST) - in case of a webhook scenario this is not simple to use.

We should allow the user to post single records to input by using a specific endpoint.

**Comment by patuwwy** [comment]
I think we could do multiple post requests with end flag set to false

**Comment by patuwwy** [comment]
`x-end-stream: false`

**Comment by patuwwy** [comment]
```
$ si topic send t1
a
b
c
d
^C
$ si topic send t1
e
f
g
h
^C
 $ si topic get t1
a
b
c
d
e
f
g
h
