### ISSUE TITLE
Improve speed of CLI

### ISSUE THREAD

**Issue by luccam-scr** [scramjetorg/transform-hub#27]
On my dev machine:
$ time si inst -h
Usage: si instance|inst [options] [command] [command]
[....]

real	0m2,985s
CLI should react faster for commands.

**Comment by MichalCz** [comment]
Can you give me the output of this command?

`cat $(which si)`

I think this is due to the fact that you installed the ts-node, so dev version of cli. CLI is compiled each time and this doesn't happen when using `npm i -g @scramjet/cli` from the repo.

Let's confirm this first.

**Comment by luccam-scr** [comment]
I installed CLI from npm and now it indeed works faster

time si inst -h
real    0m0.118s
user    0m0.129s
sys     0m0.001s
