### ISSUE TITLE
STH config should have strong validation on update.

### ISSUE THREAD

**Issue by pietrzakacper** [scramjetorg/transform-hub#279]
Similar to how config is decoded in KubernetesInstanceAdapter

**Comment by pietrzakacper** [comment]
This way we could detect several configuration problems at the time of STH startup instead of at the time of usage of the config values.

**Comment by MichalCz** [comment]
So this we should address with full DTO validation instead of just typings.

**Comment by alicja-gruzdz** [comment]
@ErykSol could you please give your opinion on the state of the config validation after your improvements?

**Comment by alicja-gruzdz** [comment]
hallelujah :)
