### ISSUE TITLE
CLI - passing arguments to CLI could me more clear

### ISSUE THREAD

**Issue by luccam-scr** [scramjetorg/transform-hub#28]
In https://github.com/scramjet-cloud-platform/scramjet-csi-dev/blob/release/0.10/packages/cli/src/lib/commands/sequence.ts#L47 is stated, that <args>are requied, however you can run sequence with emty args '[]'. It is not declared there, what is the required <args> format.

To consider:
- making <args> optional, cause they can be empty
- changing <args> format from array to list so that user can provide arguments as a separate parameters

**Comment by alicja-gruzdz** [comment]
Fixed, passing the args when starting the Instance is optional:

![Zrzut ekranu z 2022-02-11 17-52-51](https://user-images.githubusercontent.com/8177865/153633968-909d51eb-4402-48be-844b-e07e9c75848f.png)
