### ISSUE TITLE
Closed container should return 404 (Endpoint /health reports inproper status)

### ISSUE THREAD

**Issue by luccam-scr** [scramjetorg/transform-hub#30]
Endpoint informs that instance is healthy, even if instance is switched off/not running:

$ curl -v localhost:8000/api/v1/instance/d3a652c3-c1ef-4354-a227-aea764e69726/health
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /api/v1/instance/d3a652c3-c1ef-4354-a227-aea764e69726/health HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json
< Date: Fri, 23 Jul 2021 15:31:18 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
{"cpuTotalUsage":1133199115,"healthy":true,"limit":16477421568,"memoryMaxUsage":17432576,"memoryUsage":16060416,"networkRx":25148,"networkTx":0,"containerId":"bf3cadadd3e2dbcd5ac83c600c1ecdac7124d745dcc5727e4b043a04e67c697d"}

Also, here it is possible to write to input and other STH API endpoints.

**Comment by pietrzakacper** [comment]
Fixed
