### ISSUE TITLE
Topics CLI support for stdin 

### ISSUE THREAD

**Issue by pietrzakacper** [scramjetorg/transform-hub#310]
**Feature description**
Right now we can only send data to topic using a file

**Comment by patuwwy** [comment]
https://github.com/scramjetorg/transform-hub/blob/release/0.18/packages/cli/src/lib/commands/topic.ts#L23

**Comment by alicja-gruzdz** [comment]
@pietrzakacper please check in a free moment if this fixes it https://github.com/scramjetorg/transform-hub/pull/334
![Zrzut ekranu z 2022-03-09 19-59-51](https://user-images.githubusercontent.com/8177865/157514226-4c37ea56-75cc-44f0-84f6-732f20e2613a.png)
(stdout in the host is just my debuging:))
