### ISSUE TITLE
Data sent to input stream after instance start but before attaching streams should not be lost

### ISSUE THREAD

**Issue by luccam-scr** [scramjetorg/transform-hub#34]
When we run instance, for example by using CLI `seq inst start`; and when start command is completed, we need to wait another 2 sec before instance will have attached all the streams. In such case when script starts instances and immediately writes some data to them, data from first 2 seconds are lost.

I suggest to extend response of the API endpoint /start to the momen when input stream will be ready to accept data.

**Comment by MichalCz** [comment]
Checked and fixed.
