### ISSUE TITLE
Our BDD tests are not consistent

### ISSUE THREAD

**Issue by pietrzakacper** [scramjetorg/transform-hub#345]
It's becoming more and more difficult to write a BDD tests as there are a lot of different ways to do one thing.

I guess we could use a guideline or a presentation on how to write our BDD tests that would include describing the use of different abstractions like `HostClient`, `ManagerClient`, `HostsStore` etc.
Additionally some of the tests should be rewritten to use the clients that we have in-place.
Ideally we could agree on one layer of abstraction in our BDD tests, for example, we don't expose underlying URLs to gherkin code.

**Comment by pietrzakacper** [comment]
I would also consider giving up on gherkin testing and start a discussion on an appopriate solution that would lower the threshold for E2E/Integration testing for us.

**Comment by MichalCz** [comment]
Done in #529
