### ISSUE TITLE
CLI: List only the commands which are available in the given mode (development vs production)

### ISSUE THREAD

**Issue by alicja-gruzdz** [scramjetorg/transform-hub#352]
We have recently introduced in our [CLI](https://github.com/scramjetorg/transform-hub/tree/release/0.18/packages/cli) two modes (environments) of operation: `development` and `production`.

The `development` mode allows the user to interact with the STH running on a user's machine.
The `production` mode allows CLI to take the full advantage of [Scramjet Cloud Platform](https://scramjet.org/#join-beta) and run the Sequences in the Scramjet cloud.

Since the `production` mode offers additional functionalities, which are not present in the development mode, it would be user friendly to only display the CLI commands which are available in the current mode. That is, for example, if a user is in the development mode, not to display the commands related to: `space`, `hub`, `token`, `scope`. 

All credit for this idea goes to @ErykSol

**Comment by ErykSol** [comment]
Done in #364.
