### ISSUE TITLE
Topics are not properly distributed between instances on one Host when connected to Manager

### ISSUE THREAD

**Issue by pietrzakacper** [scramjetorg/transform-hub#354]
I found that when the Host is connected to CPM and we start a sequence that produces a topic (e.g. `endless-names-output`) then the topic is piped to CPM and when the consuming sequence is started (e.g. `hello-input-out`) part of the topic stream is no longer buffered in the host. So it only consumes a remainging part.

**Comment by pietrzakacper** [comment]
@alicja-gruzdz @MichalCz @patuwwy We could use some discussion on a potential solution here :wink:

**Comment by patuwwy** [comment]
not a issue anymore. fixed since SD requests data on demand.
