### ISSUE TITLE
After moving to ObjLogger, not everything is logged

### ISSUE THREAD

**Issue by pietrzakacper** [scramjetorg/transform-hub#358]
Even though different modules use their own logger instance it's not piped anywhere.
For example I had to add 
```
this.serviceDiscovery.logger.addOutput(prettyLog)
```
to `host.main()` in order to see logs from ServiceDiscovery.

**Comment by patuwwy** [comment]
Actually it is designed to be used in this way:

```this.serviceDiscovery.logger.pipe(this.logger)```
