### ISSUE TITLE
Let's use a module for URL combining, instead of working on strings

### ISSUE THREAD

**Issue by pietrzakacper** [scramjetorg/transform-hub#359]
Manually combining different parts of urls, e.g. protocol, hostname, cpm path, endpoint etc. is prone to making errors (just wasted 1.5h searching a bug caused by that :wink:)
We could use some library function similar that would for example deal with traliing slashes etc. Maybe native [nodejs URL module](https://nodejs.org/api/url.html) is sufficient idk.

**Comment by MichalCz** [comment]
Solved.
