### ISSUE TITLE
send & start CLI commands return JSON instead of ID

### ISSUE THREAD

**Issue by pietrzakacper** [scramjetorg/transform-hub#36]
In our docs we often show that we can get either sequence or instance id like that:
```bash
SEQ_ID=$(si seq send ~/package.tar.gz)   
INT_ID=$(si seq start $SEQ_ID -C "{}" $APIKEY BTC EUR)
```

but in reality these command return JSON-like output

```
> echo $SEQ_ID
SequenceClient { _id: '9922cf6f-c4e8-4742-92ab-a0a59d53a96a', host: HostClient { apiBase: 'http://127.0.0.1:8000/api/v1', client: ClientUtils { apiBase: 'http://127.0.0.1:8000/api/v1', log: [Object] } }, sequenceURL: 'sequence/9922cf6f-c4e8-4742-92ab-a0a59d53a96a' }
```

**Comment by alicja-gruzdz** [comment]
@a-tylenda do perhaps remember if we still have this anywhere in docs? I don't think so.

**Comment by pietrzakacper** [comment]
it's not in our docs anymore but this is stil a usability issue. Alhough `-` option as ID is improving the experience on that.
