### ISSUE TITLE
Inconsistent/confusing protocol handling in api urls

### ISSUE THREAD

**Issue by jan-warchol** [scramjetorg/transform-hub#372]
**Describe the bug**

When working with transform hub (and cloud platform), sometimes I have to include `http://` in the urls, and sometimes I must _not_ include it. It's confusing.

**Example: CPM url**
`--cpm-url` option for STH doesn't work when the url already starts with `http://` - it seems that the protocol is always prepended. The result is that STH cannot connect.
**Expected behavior**: either prepend protocol to the url only when it's not specified, or throw an error when the user provides url with protocol.

**Example: HostClient url**
`HostClient` does not work when the provided url doesn't have the protocol - code like this:
```
import { HostClient } from "@scramjet/api-client";
const client = new HostClient("localhost:8000/api/v1")
```
will result in a difficult to understand error like to this:
```
Error: Failed to request 'localhost:8000/api/v1/load-check' with code undefined.
          at Function.from (/home/jan/src/platform-tests/node_modules/@scramjet/src/client-error.ts:77:20)
          at ClientUtils.safeRequest (/home/jan/src/platform-tests/node_modules/@scramjet/src/client-utils.ts:96:31)
          at async default_1.<anonymous> (/home/jan/src/platform-tests/steps/steps.ts:13:13)
```
On the other hand, when you omit protocol in CLI, you get a more helpful (and immediate) error:
```
$ si config apiUrl localhost:8000/api/v1
$ si seq list
Request failed with code "undefined" status: undefined
Error: Only HTTP(S) protocols are supported
    at Function.from (/home/jan/src/transform-hub/dist/cli/node_modules/@scramjet/client-utils/client-error.js:69:16)
    at /home/jan/src/transform-hub/dist/cli/node_modules/@scramjet/client-utils/client-utils.js:36:46
    at async displayEntity (/home/jan/src/transform-hub/dist/cli/lib/output.js:30:17)
```
(only the "`undefined`" part is a bit confusing).

**Expected behavior**: either prepend protocol to the url when it's not specified, or throw an error immediately when instantiating `HostClient` with wrong url.

In general, I would expect that both places behaved similarly - either the protocol is required or not.

**Comment by MichalCz** [comment]
The protocol should always be there.
