### ISSUE TITLE
API url with trailing slash is accepted but doesn't work

### ISSUE THREAD

**Issue by jan-warchol** [scramjetorg/transform-hub#373]
**Describe the bug**
API url with trailing slash does not work, but neither `si` nor `HostClient` complain when it's specified.

**Steps to Reproduce**
```js
import { HostClient } from "@scramjet/api-client";
const client = new HostClient("localhost:8000/api/v1/")  // no error
client.getLoadCheck()  // -> this will try to request "localhost:8000/api/v1//load-check"
```
or
```bash
$ si config apiUrl http://localhost:8000/api/v1/
$ si seq list
Request failed with code "404" status: undefined
Error: Failed to request 'http://localhost:8000/api/v1//sequences' with code 404.
# [...]
```

**Expected behavior**
Either handle duplicated slashes (github does that - `https://github.com///scramjetorg//transform-hub` works just like `https://github.com/scramjetorg/transform-hub/`) or throw an error when an api url with a trailing slash is provided.

**Comment by f1ames** [comment]
I stumbled upon the same issue with `middlewareApiUrl` in `si`. Was going ot report this but you were first :+1: 

So setting it like:

```
si config set middlewareApiUrl http://127.0.0.1:7000/api/v1/
```

results in request with duplicated `/` returning 404. Using `http://127.0.0.1:7000/api/v1` works just fine.
