### ISSUE TITLE
Python Runner does not dispatch text chunks to Sequences without newline endings

### ISSUE THREAD

**Issue by pietrzakacper** [scramjetorg/transform-hub#376]
***Current behavior***
It is required for a Python sequence's input stream to either be closed or ended with a newline character in order for data to be consumed by a sequnce.

***Expected behavior***
I can send any text data and it willl be processed by a sequence

**Comment by jan-warchol** [comment]
I think that's related to the input type. If you use text, it is newline-buffered. Binary data is not.
