### ISSUE TITLE
Kubernetes Adapter Support For Both Node and Python

### ISSUE THREAD

**Issue by alicja-gruzdz** [scramjetorg/transform-hub#377]
While testing the deployments @daro1337 discovered an issue with the STH Kubernetes Adapter. 
There can be only either Node or Python specified while starting the STH. 

This is because there is one Runner Image value for Kubernetes entry in the STH config:
https://github.com/scramjetorg/transform-hub/blob/release/0.19/packages/sth-config/src/config-service.ts#L50

Excepted behavior: adapter should deduce which Runner image to choose based on the package.json information provided, like case of Process and Docker adapters.

**Comment by daro1337** [comment]
It is worth adding that the `runnerImage` variable itself should stay in order to be able to download the runner images from a private repository. We can rename it to `runnerImageRepository`
