### ISSUE TITLE
Make instance streams available after it ends

### ISSUE THREAD

**Issue by jan-warchol** [scramjetorg/transform-hub#388]
Currently all API endpoints (e.g. `/output`) become unavailable right after the instance stops running. It would be useful to be able to access them for some time.

**Comment by alicja-gruzdz** [comment]
If I remember correctly @patuwwy used to use defer in cleanup to delay destroying the CSI Controller, but it was only implemented in Docker container instance adapter and not configurable at the moment:
https://github.com/scramjetorg/transform-hub/blob/release/0.19/packages/adapters/src/docker-instance-adapter.ts#L256
https://github.com/scramjetorg/transform-hub/blob/release/0.19/packages/host/src/lib/csi-controller.ts#L225 

What would you see as the most user friendly solution?

**Comment by MichalCz** [comment]
Done.
