### ISSUE TITLE
[CLI] report version infromation

### ISSUE THREAD

**Issue by daro1337** [scramjetorg/transform-hub#395]
**Feature description**
It would be good if CLI had a version argument

```bash
$ si version
error: unknown command 'version'

$ si -v
error: unknown option '-v'
```
Suggestion:

```bash
$ si version
v0.20.0

$ si -v
v0.20.0
```

**Comment by alicja-gruzdz** [comment]
@daro1337 in the new CLI commends implemented by @ErykSol in https://github.com/scramjetorg/transform-hub/pull/364 (not merged yet) there are:
`si --version`
`si -v`
albeit as I can see they currently return undefined:
![Zrzut ekranu z 2022-04-05 09-20-11](https://user-images.githubusercontent.com/8177865/161700655-c47cbb17-903c-46ed-a8a2-82c301ef0a55.png)

@daro1337 please let us know whether this phrasing of version makes sense or you would find `si version` also useful to be added.

@ErykSol maybe the` process.env.npm_package_version` is not working and we need to go with something like in the Host:
https://github.com/scramjetorg/transform-hub/blob/release/0.19/packages/host/src/lib/host.ts#L28

**Comment by ErykSol** [comment]
Thx @alicja-gruzdz fixed according to your tip :)
