### ISSUE TITLE
CLI help: command is duplicated in the header line

### ISSUE THREAD

**Issue by jan-warchol** [scramjetorg/transform-hub#413]
**Steps to Reproduce**

```
$ npm install -g @scramjet/cli@0.20.0
$ si inst --help
Usage: si instance|inst si inst [command] [options...]
...
$ si hub --help
Usage: si hub si hub [command] [options...]
...
```
As you can see above, `si hub` is written twice.
This affects both CLI installed from source (426e02c5) and NPM version 0.20.0.

**Comment by a-tylenda** [comment]
Fixed in PR https://github.com/scramjetorg/transform-hub/pull/419
