### ISSUE TITLE
Sequences that only consume data are finished immediately

### ISSUE THREAD

**Issue by pietrzakacper** [scramjetorg/transform-hub#430]
If we have a sequence like this, that doesn't use output stream. It will be considered as finished after the function runs.
Even though the intuitive behavior would be that it wait for data on input stream.

```ts
export default function(input) {
    input.on('data', (data) => {
        saveWeatherData(data.time, data.temperature)
    })
}
```

In solving this there's a tradeoff between finishing sequences prematurely and not finishing them even though it's desired. (For example in this case, the sequence ideally should end when the input stream is ended). Also there are similar situations when a sequence is only using process.stdin and process.stdout.  
I guess a reasonable approach would be to default the output stream to `PassThrough`, if it's `undefined`. And inform users that their sequence will run indefinitely or they will have to finish them manually or using the sequence context.

**Comment by patuwwy** [comment]
IMO, one can always ```return new Promise(() => {})```

**Comment by patuwwy** [comment]
Not a bug. 

Sequence behaves as intended. To keep an Instance running You need to return Stream (Instance will be closed on Stream end) or Promise (Instance will closed on Promise resolve / reject)
