### ISSUE TITLE
CLI's NODE_ENV not recognized properly

### ISSUE THREAD

**Issue by alicja-gruzdz** [scramjetorg/transform-hub#447]
**Describe the bug**
When `NODE_ENV=development` is set, the development-mode platform commands: `space`, `hub`, `scope` are active.
In the previous CLI versions this worked:
`$ NODE_ENV=development`
```
$ si space ls
[ { id: 'org-31c9f31e-698f-4fd5-a3cd-7221741da285-manager' } ]
```

In the `si` version:
```
$ si -v
0.20.1
```

It only works when passing the env variable with the si command:
`$ NODE_ENV=development si space ls`

Thanks to @a-tylenda and @daro1337 for verifying it:

![image](https://user-images.githubusercontent.com/8177865/163410599-6821de95-3f51-4951-a880-92a9a620b557.png)

```
daro@ ~$ si -v
0.20.1
daro@ ~$ echo $NODE_ENV
development
daro@ ~$ si space ls
error: unknown command 'space'
```
![Zrzut ekranu z 2022-04-14 15-22-08](https://user-images.githubusercontent.com/8177865/163410489-4e74a59d-ecc1-4bc6-bc91-b293842b5bf3.png)

Additionally: we now how two `development` values, which are used for different functionalities. It is confusing.
We have `env: 'development'` in the `global-config.json` and `NODE_ENV=development`.
Perhaps we should rename one of them? Maybe `env: platform` - ?

**Steps to Reproduce**
1. Install CLI v. 0.20.1
2. Set: 
`NODE_ENV=development`
3. Execute:
`si space ls`

**Expected behavior**

**Version (please complete the following information):**
 - STH version: 0.20.1
 - CLI version: 0.20.1
 - node version: 16.6.1
 - os: Ubuntu

**Comment by pietrzakacper** [comment]
The CLI implementation is correct. There's an issue with the way you set the NODE_ENV variable. 
When you write
```bash
NODE_ENV=development
```
it will set this as a local variable for this shell process. The subprocesses created by this shell won't have access to that.
The proper way to set a variable for all the subprocesses is using `export` in unix:
```bash
export NODE_ENV=development
```
If you want to set a variable only for one subprocess, you have to specify it while spawning it:
```bash
NODE_ENV=development node index.js
```

**Comment by alicja-gruzdz** [comment]
Excellent, thanks @pietrzakacper
