### ISSUE TITLE
 environment variables for runner via STH

### ISSUE THREAD

**Issue by daro1337** [scramjetorg/transform-hub#451]
It would be nice to pass the environment variables for runner via STH. This will be usefull  for the kubernetes adapter. 

This would allow us to pass to the runner an environment variable like DEVELOPMENT = 1 to make the runner display the logs

Example: `sth --runner-envs="{ FOO: "1", "BAR": "2" }"`

**Comment by patuwwy** [comment]
I suggest following format:

```
sth --runner-envs="FOO=1;BAR=2"
```

**Comment by alicja-gruzdz** [comment]
https://github.com/scramjetorg/transform-hub/pull/986
