### ISSUE TITLE
[CLI] space / hub / seq / inst autocompletion

### ISSUE THREAD

**Issue by daro1337** [scramjetorg/transform-hub#453]
**Feature description**

Autocomplete works great, but I miss the autocomplete suggesting the available space / hub / sequence / instance
Currently to setup e.g space we have to list space `si space ls` then copy it's ID and paste to `si space use <space_id>` 
IMO, `si space use` should prompt and autocomplete available spaces. Similarly for `si hub use` / `si sequence use` / `si instance use`

Since the sequences are in GUID format, this should work just like in kubectl
Example from kubectl how does it work:

```
kubectl get pods -n elk elk-filebeat-<tab>
elk-filebeat-6m2l4  elk-filebeat-bp9d8  elk-filebeat-fhbjn  elk-filebeat-jhpl7  elk-filebeat-pqwfh  elk-filebeat-f74hc 
``` 
Then type elk-filebeat-f<tab>
```
kubectl get pods -n elk elk-filebeat-f<tab>
elk-filebeat-f74hc  elk-filebeat-fhbjn
```

**Comment by ErykSol** [comment]
This feature will not be developed. Hubs, spaces, sequences, instances and topics are not stored localy on system, and would require http request on every autocomplete to pass info to completer options.
