### ISSUE TITLE
STH prerunner maxMem setting doesn't seem to work

### ISSUE THREAD

**Issue by MichalCz** [scramjetorg/transform-hub#486]
**Describe the bug**

Running STH with command:

```
node ../dist/sth/bin/hub.js --prerunner-max-mem 64
```

Doesn't seem to affect the container max mem, also this test fails:

```
NO_INSTALL=1 yarn prebuild:packages &&SCRAMJET_TEST_LOG=1 yarn test:bdd --name "HUB-001 TC-013"NO_INSTALL=1 
```

**Comment by patuwwy** [comment]
`docker stats` pls

**Comment by patuwwy** [comment]
Problem with test suite. See https://github.com/scramjetorg/transform-hub/pull/627
