### ISSUE TITLE
[CLI] "si hub ls" does not return output in json format

### ISSUE THREAD

**Issue by daro1337** [scramjetorg/transform-hub#505]
**Describe the bug**
[CLI] `si hub ls` does not return output in json format, even if  format is set to json in config

1. `si config set log --format json`
2. `si hub ls`

**Steps to Reproduce**
```{
  "configVersion": 1,
  "apiUrl": "http://127.0.0.1:8000/api/v1",
  "debug": false,
  "format": "json",
  "middlewareApiUrl": "https://endpoint/api/v1",
  "env": "production",
  "scope": "",
  "token": "token-abc"
}
```

List hubs:
```
si hub ls |jq
parse error: Invalid numeric literal at line 1, column 6
```
as we can see `jq` can't parse output.

Output without jq:

```
$ si hub ls
Space: org-5cfb82c4-31d4-4f10-93f6-b441858f0396-manager
Hubs [
  {
    id: 'org-5cfb82c4-31d4-4f10-93f6-b441858f0396-host',
    info: {
      created: '2022-05-18T10:31:58.874Z',
      lastConnected: '2022-05-18T10:31:58.876Z'
    },
    healthy: true,
    isConnectionActive: true
  }

```

**Expected behavior**
valid json format from `si hub ls` so e.g `jq` can parse it when we set `format: json` in config

**Version (please complete the following information):**
 - STH version: `si -v 0.22.0`
 - node version: v16.13.2
 - os: Ubuntu 20.04.1

**Additional information like logs, screenshots etc.**

**Comment by daro1337** [comment]
@a-tylenda  same issue with `si space ls` and `si space info`
```bash
$ si space ls
[ { id: 'org-d1767369-373a-439b-9a9e-69ee55562941-manager' } ]

$ si space ls |jq
parse error: Invalid numeric literal at line 1, column 7
```

**Comment by a-tylenda** [comment]
fixed
