### ISSUE TITLE
[CLI] `si inst list` returns wrong data

### ISSUE THREAD

**Issue by a-tylenda** [scramjetorg/transform-hub#557]
**How it is now**
Listing instances with the command `si inst ls` returns a list of objects, where one object contains only info of the Instance's id and Sequence's id, like in the array below:
```json
[
  {
    id: 'c83a8311-f644-4335-a3f7-604fa28b2360',
    sequence: 'f8410330-eb9d-4b30-9084-35befbecc50f'
  },
  {
    id: 'bc4585ab-65b5-4073-ba8e-2ed12d39edf6',
    sequence: 'f8410330-eb9d-4b30-9084-35befbecc50f'
  },
  {
    id: '25985f6c-0597-4d03-b473-e40a420d9042',
    sequence: 'f8410330-eb9d-4b30-9084-35befbecc50f'
  },
  {
    id: '79f47bb2-bf8c-4953-90f5-cee5eaaf7ac0',
    sequence: 'f8410330-eb9d-4b30-9084-35befbecc50f'
  }
]
```
**How it should be**
The Instance list should return an array of objects, where each object contains more info about the Instance, like this:
```json
{
  id: 'c83a8311-f644-4335-a3f7-604fa28b2360',
  appConfig: {},
  sequenceArgs: [],
  sequence: 'f8410330-eb9d-4b30-9084-35befbecc50f',
  created: '2022-06-10T07:28:14.912Z',
  started: '2022-06-10T07:28:22.928Z',
  status: 'running'
}
```
The same info we can get under `si inst info -` command.
 
**Steps to Reproduce**

1. repo: `transform-hub`
2. branch: `devel`
3. run `yarn build:packages && yarn build:refapps`
4. run sth:  `node dist/sth/bin/hub.js`
5. make sure your config is set to localhost (`si config reset all`)
6. send and start a few Sequences: 
```
si seq send packages/reference-apps/endless-names-output.tar.gz && \
  for i in {1..10}; do si seq start - --args=[10000]; done
```
7.  `si inst ls`

**Version:**
 - STH version: { version: '0.24.2' }
 - node version: v16.13.2
 - os: Ubuntu 20.4

**Comment by patuwwy** [comment]
#559
