### ISSUE TITLE
Doesn't work on RPi Zero 2 W!

### ISSUE THREAD

**Issue by MichalCz** [scramjetorg/transform-hub#573]
**Describe the bug**

When I start the STH on Raspberry Pi Zero 2 W it works fine, I can send sequences but when I try to start a sequence STH returns `419` error code and says that there's insufficient data.

***Reproduction repo/branch***

1. `npm i -g @scramjet/sth @scramjet/cli`
2. `wget https://github.com/scramjetorg/reference-apps/releases/download/v0.24.6/endless-names-output.tar.gz`
3. `scramjet-transform-hub --runtime-adapter=process`
4. `si seq send endless-names-output.tar.gz`
5. `si seq start -`

Step 5 fails and returns the `419` http status.

**Expected behavior**

It should run the sequence

**Version (please complete the following information):**
 - STH version: 0.24.3
 - node version: 16.x
 - os: Raspberry Pi OS, April 2022.

**Comment by patuwwy** [comment]
is it fixed by https://github.com/scramjetorg/transform-hub/pull/570 ?

**Comment by MichalCz** [comment]
![terminal screenshot running a sequence on RPi Zero 2W](https://user-images.githubusercontent.com/1292420/181854550-d98fd519-e175-4a0f-a864-3316ebfd9fd8.png)
![my RPi zero on which the above seq is working](https://user-images.githubusercontent.com/1292420/181854592-88b78997-d81b-497c-9a0b-0072fb6757bf.png)

Yup, it works.
