### ISSUE TITLE
Stopping instance causes Runner to exit with error code 137

### ISSUE THREAD

**Issue by patuwwy** [scramjetorg/transform-hub#579]
https://github.com/scramjetorg/transform-hub/blob/56ab23817bf58a8f4282d8ac33691c32788de2cb/packages/runner/src/runner.ts#L250

stopping instance causes runner to exit with error code 137

IMO, stopExpected should be set to true here.
Stopping instance shouldn't cause error - It is intentional user interaction, runner should exit with 0

**Comment by MichalCz** [comment]
Yeah. I think you're right... 

This would mean removal of:

https://github.com/scramjetorg/transform-hub/blob/56ab23817bf58a8f4282d8ac33691c32788de2cb/packages/runner/src/runner.ts#L239-L242
