### ISSUE TITLE
[CLI] changing profile does not clean session config

### ISSUE THREAD

**Issue by daro1337** [scramjetorg/transform-hub#611]
**Describe the bug**
changing profile does not clean session config

**Steps to Reproduce**

within one terminal:
1. Create 2 profiles:  `si config pr create sth` , `si config pr create beta`
2. set config for sth profile and beta profile
3. use sth profile `si config pr use sth`
4. interact with sth e.g `si hub ls`
5. change profile to `beta` `si config pr use beta`
6. interact with beta, should throw error because `/tmp/.si-tmp/<session-id>/session-config.json` keeps old (`sth` profile) values

**Expected behavior**
`si config pr use <profile>` should cleanup session config.

**Version (please complete the following information):**
 - STH version: 0.26.2
 - node version: 16.x
 - os: 20.04

**Additional information like logs, screenshots etc.**

**Comment by ErykSol** [comment]
Fixed in:
https://github.com/scramjetorg/transform-hub/pull/646
