### ISSUE TITLE
[API] validate package.json and sequence.tar.gz

### ISSUE THREAD

**Issue by daro1337** [scramjetorg/transform-hub#616]
**Feature description**
Validate  if `package.json` is valid json file and `*.tar.gz` is [valid tar archive](https://github.com/scramjetorg/transform-hub/issues/525#issuecomment-1141845836)

**Comment by patuwwy** [comment]
@daro1337 we did it already, right?

**Comment by piotrek6641** [comment]
No longer relevant SequenceAdapter returns `'{"error":"Invalid pkg tar.gz archive"}\n'` when uploading corrupted tar archive and package.json is parsed to verify syntax
