### ISSUE TITLE
Instance Log

### ISSUE THREAD

**Issue by agne6ka** [scramjetorg/transform-hub#699]
**Describe the bug**

The Instance that runs for more than 24 hours doesn't respond when the log is requested.

**Steps to Reproduce**
1. Run the Instance from Sequence.
2. Wait more than 24 hours.
2. Request log for example via CLI.

**Expected behavior**

I expect to see the logs.

**Version (please complete the following information):**
 - node version: v16.15.1
 - @scramjet/manager: 0.25.1
 - CLI version 0.28.4

**Additional information like logs, screenshots etc.**

![image](https://user-images.githubusercontent.com/12500823/191499536-e3d98408-a5a1-4e3e-b3c3-3d020bc91094.png)
![image](https://user-images.githubusercontent.com/12500823/191499566-ebafda8c-2975-4c94-97ee-1d4d9ad3ce05.png)
![image](https://user-images.githubusercontent.com/12500823/191501079-4e7cb528-d22d-4cc7-a40e-65188637bfd7.png)

**Comment by alicja-gruzdz** [comment]
Thanks for catching this!

**Comment by alicja-gruzdz** [comment]
> is it responsive? any other `/instance` endpoint?

I talked to @agne6ka. Neither she nor I remember anymore. I will run the Instance now and try to replicate it. I'll let you know tomorrow.

**Comment by patuwwy** [comment]
is it responsive? :)

**Comment by alicja-gruzdz** [comment]
I ran 3 Instances for 4 days on Native, I could not replicate this issue on the new versions anymore. Hopefully it was resolved. If we reencounter it, we will create a new issue.
Versions tested on:
```
sth:0.32.1
multimanager:0.30.0-b09687d746
```
