### ISSUE TITLE
si sequence load indicator

### ISSUE THREAD

**Issue by RayNawfal** [scramjetorg/transform-hub#707]
**Feature description**
Since my sequence is around 2.2G (large model inside) it would be useful to be able to monitor the progress of uploading the file.
I'm currently trying to upload to the platform and the upload has been taking more than 10 min so far with no info on how much time it will still take.

**Comment by MichalCz** [comment]
@RayNawfal can you check this out and confirm with `--progress`?

**Comment by RayNawfal** [comment]
I updated `si` and the new version is malfunctioning. I wanted to test it on the cloud, but I can't set the token.
I'll try again after the new version is released.

**Comment by RayNawfal** [comment]
It works flawlessly. Great job by scramjet team

![Screenshot from 2022-11-03 12-05-29](https://user-images.githubusercontent.com/50368723/199706147-2d831ff7-afd0-4fe8-abce-0cd256caa26b.png)
