### ISSUE TITLE
CLI tests overwrites `si` configuration

### ISSUE THREAD

**Issue by patuwwy** [scramjetorg/transform-hub#783]
**Describe the bug**
Running CLI tests locally overwrites `si` config

**Steps to Reproduce**
1. `si config set apiUrl http://localhost:8000/api/v1
2. run bdd tests
3. `si config print` <- port is changed by tests

**Expected behavior**
Running tests doesn't impact on si config

**Version (please complete the following information):**
 - STH version: 0.31.3
 - node version: 18

**Additional information like logs, screenshots etc.**

**Comment by karoltylenda** [comment]
https://github.com/scramjetorg/transform-hub/pull/975

VDM-1494

**Comment by karoltylenda** [comment]
VDM-1494
