### ISSUE TITLE
CLI UX: inform user Store is only available on Platform

### ISSUE THREAD

**Issue by RayNawfal** [scramjetorg/transform-hub#809]
When switching to `env: development` in CLI, and trying to use `si store` commands a user must be informed that those commands can only be used in `env: production `mode.
![store_env_switch](https://user-images.githubusercontent.com/50368723/220601332-5a9d8045-cac2-48b8-876f-47e9405ac7ed.jpg)

**Comment by piotrek6641** [comment]
when trying to invoke store command on a development setup it results in a "unknown command" error: 
![screenshot](https://github.com/scramjetorg/transform-hub/assets/53794300/ed5cf86d-7dcd-4cb0-a4c8-322d206cc0e6)

Result seen in the issue will occur no matter what command is used with a flag` --help`: 
![screenshot2](https://github.com/scramjetorg/transform-hub/assets/53794300/d6c3609c-6864-4c55-8b7e-2b250f1e3a14)

This issue should be verified if it is still relevant.
