### ISSUE TITLE
[TOPIC] Default content type inconsistency 

### ISSUE THREAD

**Issue by a-tylenda** [scramjetorg/transform-hub#914]
**Describe the bug**
The content type of a topic is not the same when initializing the topic in a 3 different ways.

**Steps to Reproduce**
I initiated a topic in a 3 different ways:

1. `si topic create createdTopic`

2. `si topic send sentTopic`

3. `si topic get getTopic`

After that, I listed all topics:

`si topic ls`

```json
[
  {
    contentType: 'text/plain',
    localProvider: '',
    topic: 'createdTopic',
    topicName: 'createdTopic'
  },
  {
    contentType: 'text/plain',
    localProvider: '',
    topic: 'sentTopic',
    topicName: 'sentTopic'
  },
  {
    contentType: 'application/x-ndjson',
    localProvider: '',
    topic: 'getTopic',
    topicName: 'getTopic'
  }
]
```
**Expected behavior**
Default `contentType: 'application/x-ndjson'` is set when initiating a topic by GET request. Should be text/plain as `si topic get --help` says:

```bash
$ si topic get -h
Current profile: local
Usage: si topic get [options] <topic-name>

Get data from topic

Options:
  -t, --content-type [content-type]  Specifies type of data in topic (choices: "text/x-ndjson", "application/x-ndjson", "text/plain", "application/octet-stream", default: "text/plain")
  -h, --help
```

**Version (please complete the following information):**
STH version: 0.35.0
SI version: 0.35.0
node version: v18.15.0
os: Ubuntu 20.4

**Additional information like logs, screenshots etc.**

**Comment by ErykSol** [comment]
Tested on STH 35.2 Working
