### ISSUE TITLE
[TOPIC] Option `--content-type` in `si topic get <topicName>` does not work

### ISSUE THREAD

**Issue by a-tylenda** [scramjetorg/transform-hub#915]
**Describe the bug**
When I try to use other content type then default it id not working but only when initiating topic with `si topic get` command:

**Steps to Reproduce**
1. Create a topic by executing this command:
```bash
si topic get newTopic -t application/octet-stream
```

2. Then list topics
```bash
$ si topic ls
[
  {
    contentType: 'application/x-ndjson',
    localProvider: '',
    topic: 'newTopic',
    topicName: 'newTopic'
  }
]
```
The content type stays unchanged. Should be `application/octet-stream`.

**Expected behavior**
The content type should be possible to be overwritten when using `--content-type` or `-t` option

**Version:**

STH version: 0.35.0
SI version: 0.35.0
node version: v18.15.0
os: Ubuntu 20.4

**Comment by ErykSol** [comment]
Checked on sth 35.2. Working
