### ISSUE TITLE
Two requests when we type "si space ls"

### ISSUE THREAD

**Issue by karoltylenda** [scramjetorg/transform-hub#976]
When we type in CLI `si space ls` 
we got two responses:
`karoltylenda@karol-hp-elitebook-1040-14-inch-g9-notebook-pc:~$ si space ls`
`Request ok: https://api.scramjet.cloud/api/v1/spaces status: 200 OK`
`Request ok: https://api.scramjet.cloud/api/v1/spaces status: 200 OK`
`[ { id: 'org-5008b9a9-72a2-4ce0-8b22-65aae2f74588-manager' } ]`

**Comment by alicja-gruzdz** [comment]
@gzukowski could you please try to replicate if it is still the case?

**Comment by gzukowski** [comment]
This occurs only in the debug mode. It is the log on the path to determined endpoint.
